DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
ID BIGINT(19) NOT NULL,
USERNAME VARCHAR(255),
FIRSTNAME VARCHAR(255),
LASTNAME VARCHAR(255),
);

CREATE TABLE EXERCISE (
ID BIGINT(19) NOT NULL,
DESCRIPTION VARCHAR(255),
DURATION VARCHAR(255),
DATE TIMESTAMP(23, 10),
);